plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'ext/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Steepfile'

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/ExampleLength:
  Max: 16

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/dartsclone_spec.rb'

